name = "thingstodo"
type = "webpack"

account_id = "102a9bfb4fe63b8acfe40a335703d163"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-09"
kv_namespaces = [
         { binding = "CACHE", preview_id = "061ddf9f7bb641b79059fb4ed9e2438f", id = "5f88e4acaf7e4c3285d3d3f928223a33" }
]
