name = "thingstodo"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-09"
kv_namespaces = [
         { binding = "CACHE", preview_id = "061ddf9f7bb641b79059fb4ed9e2438f", id = "7e578e4fd9204cc1a36636e3177135d3" }
]